trigger: none

pool: Default

steps:
- task: 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'First_service_connection'
    backendAzureRmStorageAccountName: 'satishstg111222'
    backendAzureRmContainerName: 'newcontainer'
    backendAzureRmKey: 'terraform.tfsate'
- task: 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'First_service_connection'

- task: 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'First_service_connection'